TEXTUREPACKER := /Applications/TexturePacker.app/Contents/MacOS/TexturePacker

SHEET := player.png
DATA := player.json

.PHONY: all

all:
	$(TEXTUREPACKER) --format json --data $(DATA) --sheet $(SHEET) player.tps
