[tool_alias]
optivorbis = "github:OptiVorbis/OptiVorbis"

[tools]
cmake = "latest"
conan = "latest"
optivorbis = { version = "0.3.2", rename_exe = "optivorbis" }
oxipng = "10.2.1"
pre-commit = "latest"
