name: Linux

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - "tools/**"
  pull_request:
    branches:
      - main
    paths:
      - "tools/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Conan
        run: |
          pip install conan
          conan profile detect --force

      - name: Cache Conan packages
        uses: actions/cache@v5
        with:
          path: ~/.conan2/p
          key: conan-${{ runner.os }}-tools-${{ hashFiles('tools/conanfile.py') }}
          restore-keys: |
            conan-${{ runner.os }}-tools-

      - name: Build pack tool
        working-directory: tools
        run: |
          conan install . --output-folder=build --build=missing --settings build_type=Release
          cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
