name: macOS

on:
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - "src/**"
      - "tools/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"
      - "tools/**"

jobs:
  build:
    runs-on: macos-latest

    env:
      CMAKE_POLICY_VERSION_MINIMUM: "3.5"

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.2.0

      - name: Setup Conan
        run: |
          uv tool install conan
          uv tool run conan profile detect --force

      - name: Configure tools & CMake
        run: |
          cat <<'EOF' >> ~/.conan2/profiles/default
          [replace_tool_requires]
          meson/*: meson/[*]
          pkgconf/*: pkgconf/[*]

          [tool_requires]
          !cmake/*: cmake/[>=4 <5]
          EOF

      - name: Cache Conan packages
        uses: actions/cache@v5
        with:
          path: ~/.conan2/p
          key: conan-${{ runner.os }}-${{ hashFiles('conanfile.py', 'recipes/**') }}
          restore-keys: |
            conan-${{ runner.os }}-

      - name: Export local recipes
        run: |
          uv tool run conan export recipes/luajit --version=2.1-20260616

      - name: Install dependencies
        run: uv tool run conan install . --output-folder=build --build=missing --settings compiler.cppstd=23 --settings build_type=Release

      - name: Build
        run: |
          cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release --verbose

      - name: Package cartridge
        run: uv run tools/pack.py cartridge

      - name: Collect artifacts
        run: |
          mkdir -p artifact
          cp build/carimbo artifact/
          cp cartridge.rom artifact/
          cp tools/pack.py artifact/
          cp tools/unpack.py artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: artifact/
