name: Windows

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - CMakeLists.txt
      - conanfile.py
      - recipes/**
      - .github/**

jobs:
  build:
    runs-on: windows-latest

    env:
      CMAKE_POLICY_VERSION_MINIMUM: "3.5"

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          cache-dependency-glob: |
            tools/pack.py
            assets/tools/*.py

      - name: Setup Conan
        run: |
          uv tool install conan
          uv tool run conan profile detect --force

      - name: Configure tools & CMake
        run: |
          cat <<'EOF' >> ~/.conan2/profiles/default
          [replace_tool_requires]
          meson/*: meson/[*]
          pkgconf/*: pkgconf/[*]

          [tool_requires]
          !cmake/*: cmake/[>=4 <5]
          EOF

      - name: Cache Conan packages
        uses: actions/cache@v6
        with:
          path: ~/.conan2/p
          key: conan-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('conanfile.py', 'recipes/**', '.github/conan/**') }}
          restore-keys: |
            conan-${{ runner.os }}-${{ runner.arch }}-

      - name: Export local recipes
        run: |
          uv tool run conan export recipes/luajit --version=2.1-20260908

      - name: Install dependencies
        run: uv tool run conan install . --output-folder=build --build=missing --profile:host=.github/conan/windows

      - name: Build
        run: |
          cmake -Bbuild \
            -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DVERSION="${{ github.sha }}" \
            -DCMAKE_C_FLAGS_RELEASE="/O2 /Z7 /DNDEBUG" \
            -DCMAKE_CXX_FLAGS_RELEASE="/O2 /Z7 /DNDEBUG" \
            -DCMAKE_EXE_LINKER_FLAGS_RELEASE="/DEBUG:FULL /OPT:REF /OPT:ICF /INCREMENTAL:NO /PDBALTPATH:carimbo.pdb"
          cmake --build build --config Release --verbose

      - name: Upload symbols
        uses: actions/upload-artifact@v7
        with:
          name: windows-symbols
          path: build/Release/carimbo.pdb
          if-no-files-found: error

      - name: Generate assets
        run: uv run assets/tools/run.py

      - name: Package cartridge
        run: uv run tools/pack.py cartridge

      - name: Collect artifacts
        run: |
          mkdir -p artifact
          cp build/Release/carimbo.exe artifact/
          cp cartridge.rom artifact/
          cp tools/pack.py artifact/
          cp tools/unpack.py artifact/

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: build
          path: artifact/
